FROM $DOCKER_REPO/node:8.0.0

COPY package.json .
RUN npm install

COPY config config
COPY helpers helpers
COPY json-data json-data
COPY sequelize-models sequelize-models
COPY CategoryIngestionService.js CategoryIngestionService.js
#COPY server.js .
#COPY erroneous-data-insertion.js .
#COPY author-count-server.js .
COPY category-insertion.js .
CMD [ "npm", "start" ]
# CMD ["node", "/usr/src/app/node_modules/.bin/mocha"]
