FROM $DOCKER_REPO/node:8.0.0

COPY package.json .
RUN npm install

COPY config config
COPY helpers helpers
COPY sequelize-models sequelize-models
COPY Category.js Category.js
COPY server.js .

CMD [ "npm", "start" ]
# CMD ["node", "/usr/src/app/node_modules/.bin/mocha"]
